FROM public.ecr.aws/lambda/python:3.9

# 設置工作目錄
WORKDIR ${LAMBDA_TASK_ROOT}

# 複製程式碼和依賴檔案
COPY optimize_handler.py .
COPY utils/ utils/
COPY requirements.txt .

# 安裝依賴
RUN pip install -r requirements.txt --no-cache-dir

# 設置環境變數
ARG STAGE
ENV STAGE=${STAGE}

# 設置Lambda處理函數
CMD [ "optimize_handler.handler" ]